# Etapa de construcción para la aplicación ASP.NET Core
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copiar csproj y restaurar las dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar el resto de los archivos del proyecto
COPY . ./

# Construir la aplicación
RUN dotnet publish -c Release -o out

# Etapa de ejecución para la aplicación ASP.NET Core
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build-env /app/out .
EXPOSE 80
ENTRYPOINT ["dotnet", "VueCineApi.dll"]
